default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "waste_management_default")  %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "waste_management_default")  %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "waste_management_default")  %>
